[2025-06-26T12:55:59.927+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-26T12:55:59.967+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: loan_credit_ml.load_data scheduled__2024-10-01T03:00:00+00:00 [queued]>
[2025-06-26T12:55:59.980+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: loan_credit_ml.load_data scheduled__2024-10-01T03:00:00+00:00 [queued]>
[2025-06-26T12:55:59.981+0000] {taskinstance.py:2306} INFO - Starting attempt 3 of 4
[2025-06-26T12:56:00.002+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): load_data> on 2024-10-01 03:00:00+00:00
[2025-06-26T12:56:00.036+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'loan_credit_ml', 'load_data', 'scheduled__2024-10-01T03:00:00+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/loan_ml_pipeline_dag.py', '--cfg-path', '/tmp/tmps9o50j2w']
[2025-06-26T12:56:00.041+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=202) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-26T12:56:00.043+0000] {standard_task_runner.py:91} INFO - Job 88: Subtask load_data
[2025-06-26T12:56:00.043+0000] {standard_task_runner.py:63} INFO - Started process 212 to run task
[2025-06-26T12:56:00.133+0000] {task_command.py:426} INFO - Running <TaskInstance: loan_credit_ml.load_data scheduled__2024-10-01T03:00:00+00:00 [running]> on host 1874434f82c9
[2025-06-26T12:56:00.289+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='loan_credit_ml' AIRFLOW_CTX_TASK_ID='load_data' AIRFLOW_CTX_EXECUTION_DATE='2024-10-01T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='3' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-01T03:00:00+00:00'
[2025-06-26T12:56:00.291+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-26T12:56:11.728+0000] {logging_mixin.py:188} INFO - [✓] Dataset 2023-01-01 → 2024-10-01: 10,971 rows, 73 features.
[2025-06-26T12:56:11.739+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-06-26T12:56:11.740+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-26T12:56:11.757+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=loan_credit_ml, task_id=load_data, run_id=scheduled__2024-10-01T03:00:00+00:00, execution_date=20241001T030000, start_date=20250626T125559, end_date=20250626T125611
[2025-06-26T12:56:11.841+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-26T12:56:11.871+0000] {taskinstance.py:3503} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-06-26T12:56:11.875+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
