[2025-06-26T13:01:47.065+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-26T13:01:47.108+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: loan_credit_ml.monitoring scheduled__2024-10-01T03:00:00+00:00 [queued]>
[2025-06-26T13:01:47.125+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: loan_credit_ml.monitoring scheduled__2024-10-01T03:00:00+00:00 [queued]>
[2025-06-26T13:01:47.126+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-26T13:01:47.148+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): monitoring> on 2024-10-01 03:00:00+00:00
[2025-06-26T13:01:47.169+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'loan_credit_ml', 'monitoring', 'scheduled__2024-10-01T03:00:00+00:00', '--job-id', '96', '--raw', '--subdir', 'DAGS_FOLDER/loan_ml_pipeline_dag.py', '--cfg-path', '/tmp/tmpu8383ge8']
[2025-06-26T13:01:47.173+0000] {standard_task_runner.py:91} INFO - Job 96: Subtask monitoring
[2025-06-26T13:01:47.176+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=532) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-26T13:01:47.177+0000] {standard_task_runner.py:63} INFO - Started process 542 to run task
[2025-06-26T13:01:47.255+0000] {task_command.py:426} INFO - Running <TaskInstance: loan_credit_ml.monitoring scheduled__2024-10-01T03:00:00+00:00 [running]> on host 1874434f82c9
[2025-06-26T13:01:47.398+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='loan_credit_ml' AIRFLOW_CTX_TASK_ID='monitoring' AIRFLOW_CTX_EXECUTION_DATE='2024-10-01T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-01T03:00:00+00:00'
[2025-06-26T13:01:47.400+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-26T13:01:47.963+0000] {logging_mixin.py:188} INFO - [✓] Processed snapshot 2024-10
[2025-06-26T13:01:47.982+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-26T13:01:47.982+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/loan_ml_pipeline_dag.py", line 83, in monitoring_task
    monitoring.run_monitoring()
  File "/opt/airflow/utils/monitoring.py", line 119, in run_monitoring
    df_summary.to_parquet(MON_FILE, index=False)
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/util/_decorators.py", line 333, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/core/frame.py", line 3113, in to_parquet
    return to_parquet(
           ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 480, in to_parquet
    impl.write(
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 198, in write
    path_or_handle, handles, filesystem = _get_path_or_handle(
                                          ^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/parquet.py", line 140, in _get_path_or_handle
    handles = get_handle(
              ^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/pandas/io/common.py", line 882, in get_handle
    handle = open(handle, ioargs.mode)
             ^^^^^^^^^^^^^^^^^^^^^^^^^
PermissionError: [Errno 13] Permission denied: 'data_mart/gold/monitoring/monitoring_summary.parquet'
[2025-06-26T13:01:48.012+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=loan_credit_ml, task_id=monitoring, run_id=scheduled__2024-10-01T03:00:00+00:00, execution_date=20241001T030000, start_date=20250626T130147, end_date=20250626T130148
[2025-06-26T13:01:48.032+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 96 for task monitoring ([Errno 13] Permission denied: 'data_mart/gold/monitoring/monitoring_summary.parquet'; 542)
[2025-06-26T13:01:48.076+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-26T13:01:48.106+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-26T13:01:48.111+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-06-26T13:17:53.644+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-26T13:17:53.686+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: loan_credit_ml.monitoring scheduled__2024-10-01T03:00:00+00:00 [queued]>
[2025-06-26T13:17:53.698+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: loan_credit_ml.monitoring scheduled__2024-10-01T03:00:00+00:00 [queued]>
[2025-06-26T13:17:53.700+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-26T13:17:53.718+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): monitoring> on 2024-10-01 03:00:00+00:00
[2025-06-26T13:17:53.731+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'loan_credit_ml', 'monitoring', 'scheduled__2024-10-01T03:00:00+00:00', '--job-id', '105', '--raw', '--subdir', 'DAGS_FOLDER/loan_ml_pipeline_dag.py', '--cfg-path', '/tmp/tmpll7yzm1g']
[2025-06-26T13:17:53.734+0000] {standard_task_runner.py:91} INFO - Job 105: Subtask monitoring
[2025-06-26T13:17:53.736+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=482) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-26T13:17:53.737+0000] {standard_task_runner.py:63} INFO - Started process 492 to run task
[2025-06-26T13:17:53.805+0000] {task_command.py:426} INFO - Running <TaskInstance: loan_credit_ml.monitoring scheduled__2024-10-01T03:00:00+00:00 [running]> on host f73c0c6d85d6
[2025-06-26T13:17:53.923+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='loan_credit_ml' AIRFLOW_CTX_TASK_ID='monitoring' AIRFLOW_CTX_EXECUTION_DATE='2024-10-01T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-01T03:00:00+00:00'
[2025-06-26T13:17:53.925+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-26T13:17:54.923+0000] {logging_mixin.py:188} INFO - [✓] Processed snapshot 2024-10
[2025-06-26T13:17:54.931+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-26T13:17:54.932+0000] {taskinstance.py:2905} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 401, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 235, in execute
    return_value = self.execute_callable()
                   ^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/python.py", line 252, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/airflow/dags/loan_ml_pipeline_dag.py", line 83, in monitoring_task
    monitoring.run_monitoring()
  File "/opt/airflow/utils/monitoring.py", line 121, in run_monitoring
    run_ts   = datetime.utcnow().strftime("%Y%m%d_%H%M%S")
               ^^^^^^^^
NameError: name 'datetime' is not defined. Did you forget to import 'datetime'
[2025-06-26T13:17:54.972+0000] {taskinstance.py:1206} INFO - Marking task as UP_FOR_RETRY. dag_id=loan_credit_ml, task_id=monitoring, run_id=scheduled__2024-10-01T03:00:00+00:00, execution_date=20241001T030000, start_date=20250626T131753, end_date=20250626T131754
[2025-06-26T13:17:55.004+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 105 for task monitoring (name 'datetime' is not defined; 492)
[2025-06-26T13:17:55.039+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-06-26T13:17:55.086+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-26T13:17:55.091+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-06-26T13:26:51.436+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-26T13:26:51.494+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: loan_credit_ml.monitoring scheduled__2024-10-01T03:00:00+00:00 [queued]>
[2025-06-26T13:26:51.522+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: loan_credit_ml.monitoring scheduled__2024-10-01T03:00:00+00:00 [queued]>
[2025-06-26T13:26:51.528+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-26T13:26:51.566+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): monitoring> on 2024-10-01 03:00:00+00:00
[2025-06-26T13:26:51.606+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'loan_credit_ml', 'monitoring', 'scheduled__2024-10-01T03:00:00+00:00', '--job-id', '110', '--raw', '--subdir', 'DAGS_FOLDER/loan_ml_pipeline_dag.py', '--cfg-path', '/tmp/tmp0yxk1atl']
[2025-06-26T13:26:51.609+0000] {standard_task_runner.py:91} INFO - Job 110: Subtask monitoring
[2025-06-26T13:26:51.614+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=403) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-26T13:26:51.615+0000] {standard_task_runner.py:63} INFO - Started process 413 to run task
[2025-06-26T13:26:51.678+0000] {task_command.py:426} INFO - Running <TaskInstance: loan_credit_ml.monitoring scheduled__2024-10-01T03:00:00+00:00 [running]> on host 408a45b37ace
[2025-06-26T13:26:51.815+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='loan_credit_ml' AIRFLOW_CTX_TASK_ID='monitoring' AIRFLOW_CTX_EXECUTION_DATE='2024-10-01T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-01T03:00:00+00:00'
[2025-06-26T13:26:51.817+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-26T13:26:52.474+0000] {logging_mixin.py:188} INFO - [✓] Processed snapshot 2024-10
[2025-06-26T13:26:52.511+0000] {logging_mixin.py:188} INFO - [✓] Monitoring summary saved to data_mart/gold/monitoring/monitoring_20250626_132652.parquet
[2025-06-26T13:26:52.511+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-06-26T13:26:52.512+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-26T13:26:52.525+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=loan_credit_ml, task_id=monitoring, run_id=scheduled__2024-10-01T03:00:00+00:00, execution_date=20241001T030000, start_date=20250626T132651, end_date=20250626T132652
[2025-06-26T13:26:52.583+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-26T13:26:52.605+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-26T13:26:52.610+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-06-26T14:01:22.121+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-26T14:01:22.156+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: loan_credit_ml.monitoring scheduled__2024-10-01T03:00:00+00:00 [queued]>
[2025-06-26T14:01:22.168+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: loan_credit_ml.monitoring scheduled__2024-10-01T03:00:00+00:00 [queued]>
[2025-06-26T14:01:22.169+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-26T14:01:22.186+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): monitoring> on 2024-10-01 03:00:00+00:00
[2025-06-26T14:01:22.201+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'loan_credit_ml', 'monitoring', 'scheduled__2024-10-01T03:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/loan_ml_pipeline_dag.py', '--cfg-path', '/tmp/tmpt2sroqlg']
[2025-06-26T14:01:22.204+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask monitoring
[2025-06-26T14:01:22.205+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=375) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-26T14:01:22.207+0000] {standard_task_runner.py:63} INFO - Started process 385 to run task
[2025-06-26T14:01:22.275+0000] {task_command.py:426} INFO - Running <TaskInstance: loan_credit_ml.monitoring scheduled__2024-10-01T03:00:00+00:00 [running]> on host ab9233100691
[2025-06-26T14:01:22.416+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='loan_credit_ml' AIRFLOW_CTX_TASK_ID='monitoring' AIRFLOW_CTX_EXECUTION_DATE='2024-10-01T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-01T03:00:00+00:00'
[2025-06-26T14:01:22.418+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-26T14:01:23.044+0000] {logging_mixin.py:188} INFO - [✓] Processed snapshot 2024-10
[2025-06-26T14:01:23.093+0000] {logging_mixin.py:188} INFO - [✓] Monitoring summary saved to data_mart/gold/monitoring/monitoring_20250626_140123.parquet
[2025-06-26T14:01:23.094+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-06-26T14:01:23.095+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-26T14:01:23.108+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=loan_credit_ml, task_id=monitoring, run_id=scheduled__2024-10-01T03:00:00+00:00, execution_date=20241001T030000, start_date=20250626T140122, end_date=20250626T140123
[2025-06-26T14:01:23.146+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-26T14:01:23.169+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-26T14:01:23.174+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
[2025-06-26T14:17:16.244+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-06-26T14:17:16.290+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: loan_credit_ml.monitoring scheduled__2024-10-01T03:00:00+00:00 [queued]>
[2025-06-26T14:17:16.301+0000] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: loan_credit_ml.monitoring scheduled__2024-10-01T03:00:00+00:00 [queued]>
[2025-06-26T14:17:16.302+0000] {taskinstance.py:2306} INFO - Starting attempt 1 of 2
[2025-06-26T14:17:17.918+0000] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): monitoring> on 2024-10-01 03:00:00+00:00
[2025-06-26T14:17:18.746+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'loan_credit_ml', 'monitoring', 'scheduled__2024-10-01T03:00:00+00:00', '--job-id', '5', '--raw', '--subdir', 'DAGS_FOLDER/loan_ml_pipeline_dag.py', '--cfg-path', '/tmp/tmpu1py7ir5']
[2025-06-26T14:17:18.749+0000] {standard_task_runner.py:91} INFO - Job 5: Subtask monitoring
[2025-06-26T14:17:18.749+0000] {logging_mixin.py:188} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61 DeprecationWarning: This process (pid=375) is multi-threaded, use of fork() may lead to deadlocks in the child.
[2025-06-26T14:17:18.751+0000] {standard_task_runner.py:63} INFO - Started process 385 to run task
[2025-06-26T14:17:19.121+0000] {task_command.py:426} INFO - Running <TaskInstance: loan_credit_ml.monitoring scheduled__2024-10-01T03:00:00+00:00 [running]> on host 0192db86dfc6
[2025-06-26T14:17:19.236+0000] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='data-team' AIRFLOW_CTX_DAG_ID='loan_credit_ml' AIRFLOW_CTX_TASK_ID='monitoring' AIRFLOW_CTX_EXECUTION_DATE='2024-10-01T03:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-10-01T03:00:00+00:00'
[2025-06-26T14:17:19.238+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-06-26T14:17:19.855+0000] {logging_mixin.py:188} INFO - [✓] Processed snapshot 2024-10
[2025-06-26T14:17:19.937+0000] {logging_mixin.py:188} INFO - [✓] Monitoring summary saved to data_mart/gold/monitoring/monitoring_20250626_141719.parquet
[2025-06-26T14:17:19.938+0000] {python.py:237} INFO - Done. Returned value was: None
[2025-06-26T14:17:19.939+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-06-26T14:17:19.955+0000] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=loan_credit_ml, task_id=monitoring, run_id=scheduled__2024-10-01T03:00:00+00:00, execution_date=20241001T030000, start_date=20250626T141716, end_date=20250626T141719
[2025-06-26T14:17:20.013+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2025-06-26T14:17:20.034+0000] {taskinstance.py:3503} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-06-26T14:17:20.040+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
